### ISSUE TITLE
Simplify input colors

### ISSUE THREAD

**Issue by nikku** [camunda/camunda-modeler#3540]
### What shall we do

We gradually want to move to a simpler, unified color scheme, taking [Carbon](https://carbondesignsystem.com/guidelines/color/overview/) as a role model:

* [ ] diagram-js-direct-editing
* [ ] properties-panel
* [ ] diagram-js + bpmn-js (popup menu, ...) 

### Additional Input

Minimal color changes proposed here: https://camunda.slack.com/archives/GP70M0J6M/p1680511330435669?thread_ts=1680249426.189479&cid=GP70M0J6M.

**Comment by nikku** [comment]
```scss

.bio-properties-panel {
  --select-template-background-color: var(--cds-blue-60);
  --select-template-hover-background-color: var(--cds-blue-70);
  --input-focus-background-color: var(--color-white);
  --input-focus-border-color: var(--cds-blue-60);
  --font-family: inherit;
  --font-family-monospace: inherit;
  background: var(--color-white);
}

.bio-properties-panel-group-header-button.bio-properties-panel-add-entry:hover {
  background-color: var(--cds-blue-60);
}

.djs-parent {
  --popup-search-focus-border-color: var(--cds-blue-60);
  --popup-search-focus-background-color: var(--color-white);
}
```
